apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-staging 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-staging.yaml
    path: helm-nginx
    repoURL: https://github.com/aungzanbaw/cloud_native_demo
    targetRevision: HEAD